# Site settings
title: N.E.T. Results
email: info@noexcusetrainingresults.com
description: > # this means to ignore newlines until "baseurl:"
  Jess DeHart is a certified RRCA Running coachand NASM certified personal trainer.
  Jess understands that strength and endurance do not come from physical capacity.
  They come from the willingness and tenacity to set a goal and exceed it. Let Jess help you achieve your N.E.T. Results.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://wwww.noexcusetrainingresults.com # the base hostname & protocol for your site

# User setting
owner: Jess DeHart
email: info@noexcusetrainingresults.com
facebook_username: noexcusetrainingresults
#twitter_username:
#github_username:
address:
  - line: 473 Lake Ave S
  - line: Nesconset, NY 11767
  # Feel free to add more lines here
telephone: 516-909-6271
copyright: BlackrockDigital &amp Volny

# API settings
google_api_key:

# Build settings
markdown: kramdown
